create or replace TRIGGER T_INSERT_CARDS 
AFTER INSERT OR UPDATE OF COLOR,FP,PLAYER ON WORLDCUP_CARDS 
BEGIN
  P_INSERT_PLAYERS();
END;

create or replace TRIGGER T_INSERT_GOALS 
AFTER INSERT OR UPDATE OF ASSIST,PLAYER,TYPE ON WORLDCUP_GOALS 
BEGIN
  P_INSERT_PLAYERS();
END;

create or replace TRIGGER T_INSERT_RESULTS 
AFTER INSERT OR UPDATE OF TEAM_1_SCORE,TEAM_2_SCORE ON WORLDCUP_MATCHES 
BEGIN
  P_INSERT_RESULTS();
  P_POPULATE_GROUPS();
END;